---
semi: true
overrides:
  - files: "**/*.{ts,js}"
    options:
      trailingComma: all
      tabWidth: 2
      semi: true
      singleQuote: true
      quoteProps: as-needed
      bracketSpacing: true
      bracketSameLine: true
      arrowParens: avoid
