---
name: Build and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build Tests - Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install
        run: yarn install

      - name: Compile
        run: yarn run build

      - name: Start Bugzilla
        run: ./itest/start_container.sh

      - name: Test
        run: yarn jest -c jest.ci.config.js --coverage

      - name: Codecov
        if: ${{ matrix.node-version == '18.x' }}
        uses: codecov/codecov-action@v3
