---
name: Deploy Test Containers

on:
  push:
    branches: [main]
    paths:
      - itest/container/*
      - .github/workflows/test-container.yml
  pull_request:
    branches: [main]
    paths:
      - itest/container/*
      - .github/workflows/test-container.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Deploy Docker Image - Test
    runs-on: ubuntu-latest

    permissions:
      packages: write
      deployments: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.dockerfile }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        config:
          - dockerfile: itest/container/Dockerfile
            context: itest/container
            tag: integration
            deployment-environment-identifier: Integration Container

    timeout-minutes: 60

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
        name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ matrix.config.deployment-environment-identifier }}

      - name: Build and Push Container
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.config.dockerfile }}
          context: ${{ matrix.config.context }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.config.tag }}:latest
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}

      - if: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
        name: Update deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }}
